
- name: Install zeppelin
  become: yes
  become_user: vagrant
  command: yay --noconfirm  --answeredit none -S apache-zeppelin

- name: Install JDK8
  become: yes
  become_user: vagrant
  command: yay --noconfirm  --answeredit none -S jdk8 --noconfirm

- name: Default java
  become: yes
  become_user: root
  command:  archlinux-java set java-8-jdk
